# global:
#   scrape_interval: 15s

# scrape_configs:
#   - job_name: node
#     static_configs:
#       - targets: ["localhost:9090", "localhost:9091"]
global:
  scrape_interval: 30s # Example of setting scrape interval to 30 seconds
  scrape_timeout: 15s # Example of setting scrape timeout to 15 seconds

scrape_configs:
  - job_name: "prometheus"
    # scrape_interval: 1m
    static_configs:
      - targets: ["localhost:9090"]

  # - job_name: 'volume_exporter'
  #   metrics_path: /metrics
  #   static_configs:
  #   - targets: ['volume_exporter:9888']
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: "sql_exporter"
    metrics_path: /metrics
    static_configs:
      - targets: ["sql_exporter:9399"]
    # scrape_timeout: 20s # Override global timeout for this specific job
